name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                compiler: [gcc, clang]
        env:
            CC: ${{ matrix.compiler }}
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get update && sudo apt-get install -y gcc-multilib cpio qemu-system-x86 grub2 mtools xorriso
            - run: make EXTRA_CFLAGS="-Werror"
            - run: nm -n kernel/kernel | awk 'NF==3'
            - run: make test
              timeout-minutes: 3
            - run: grub-file --is-x86-multiboot kernel/kernel
            - run: make disk_image
    ubsan:
        runs-on: ubuntu-24.04
        env:
            CC: gcc
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get update && sudo apt-get install -y gcc-multilib cpio qemu-system-x86
            - run: make EXTRA_CFLAGS="-Werror -fsanitize=undefined"
            - run: make test
              timeout-minutes: 5
