name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                compiler: [gcc, clang]
        env:
            CC: ${{ matrix.compiler }}
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt-get update && sudo apt-get install -y gcc-multilib cpio qemu-system-x86 grub2 mtools xorriso
            - run: make test
              timeout-minutes: 1
            - run: grub-file --is-x86-multiboot kernel/kernel
            - run: make disk_image
